### ========================================
### FITNESS MANAGEMENT SYSTEM - API TESTING
### ========================================
### Base URL Configuration

@baseUrl = http://localhost:5000
@apiUrl = {{baseUrl}}/api
### Token Variables (to be set after login)

@athleteToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTE2ZTMxMGEwMWNhMmZlYzRkN2NkZSIsInJvbGUiOiJhdGhsZXRlIiwiaWF0IjoxNzU5ODMzMzYwLCJleHAiOjE3NTk4MzY5MDB9.nBRLx_neSBQNwLJbv12I38LiCbF3MiIjy1n4XXswJl8
@coachToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTRlYmMyMGY5MjI3OWY2ODk2ODdiZSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTc1OTgzMzAyNiwiZXhwIjoxNzU5ODM2NTY2fQ.Vgc3tQwnk5qdQb3zopBb4PY4b9Ba8bB5km74jsJ2QF8
@gymToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTRlYmYwMGY5MjI3OWY2ODk2ODdjMSIsInJvbGUiOiJneW0iLCJpYXQiOjE3NTk4MzMwNzIsImV4cCI6MTc1OTgzNjYxMn0.GZeS_FCtbBUefvgLa06_yPqfp0XRHJTo-TPDmDrr3sQ
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTY0MGU0NGFhMzM4NWJmZDBjNzQ3MyIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTkyMTM4NSwiZXhwIjoxNzU5OTIyMjg1fQ.-pb10TQDCUARxkNxmmu78QzW_4Ck3PrMi1SCSVx06Ko
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTRlNDczMjM1NGM1Y2ZlMzA0MmQzYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTgzMTIwMSwiZXhwIjoxNzU5ODMyMTAxfQ.gX8hEgWjZOUwQycHMlzFV2Vb0_s8sCErnEjJ-XEzsEw


### ========================================
### USER REGISTRATION (SIGNUP)
### ========================================

###  Register Athlet
POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "name": "saad chaanoune",
  "email": "youssrauserq232@test.com",
  "password": "BACC2023!a2",
  "role": "athlete"  
}

###  Register Coach  
POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "name": "saad hamdi",
  "email": "saadhamdi@test.com",
  "password": "CoachPass123!",
  "role": "coach",
  "gender": "male",
  "cin": "BB229924",
  "years_of_experience": 10
}

###  Register Coach  
POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "name": "saad hamdi",
  "email": "saadhamdi@admin.com",
  "password": "CoachPass123!",
  "role": "admin",
  "gender": "male"
}
###  Register Gym
POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "name": "Fitness Center marena",
  "email": "hydrogym@test.com",
  "password": "GymPass123!",
  "role": "gym",
  "gender": "male"
}


###  Login as Athlete
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "yassineuser1@test.com",
  "password": "BACC2023!a"
}

###  Login as Coach
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "coachyassine@test.com",
  "password": "CoachPass123!"
}

###  Login as Gym
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "gym@test.com",
  "password": "GymPass123!"
}

###  Login as Admin
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "saadhamdi@admin.com",
  "password": "CoachPass123!"
}

# After you run the request above, uncomment the following line to capture the token from the response:

### ========================================
### TOKEN MANAGEMENT
### ========================================

###  Refresh Token 
POST {{apiUrl}}/auth/refresh
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTE2ZTMxMGEwMWNhMmZlYzRkN2NkZSIsImlhdCI6MTc1OTgzMzMzMSwiZXhwIjoxNzYwNDM4MTMxfQ.GjU6wFPkM-3kN-TAxUopnPeosVhk8gbd9AnWeY0ikJkeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTYzZDQ2NGFhMzM4NWJmZDBjNzQ1NiIsImlhdCI6MTc1OTkxOTg0NiwiZXhwIjoxNzYwNTI0NjQ2fQ.9Eo0A2IeAegTQdwuNlicBgSrSdZ7Lgnq297Lwm1ixls

###  Logout
POST {{apiUrl}}/auth/logout
Content-Type: application/json
Authorization: Bearer {{adminToken}}



### ========================================
### USER MANAGEMENT
### ========================================

###  Create User (Public)
POST {{apiUrl}}/users
Content-Type: application/json

{
  "name": "Test User",
  "email": "saaduser@test.com",
  "password": "TestPass123!",
  "gender": "female"
}
###  Get User by ID (Owner or Admin/Coach/Gym)
GET {{apiUrl}}/users/6909e844b86e601c6bbdceaf
Authorization: Bearer {{adminToken}}
Content-Type: application/json

###  Update User (Owner or Admin)
PUT {{apiUrl}}/users/68e3a1041801326ac6145879
Authorization: Bearer {{adminToken}}  
Content-Type: application/json

{
  "name": "Updated Name",
  "height": 185,
  "weight": 90,
  "certificates": 
    {
      "title": "Personal Trainer Certificate",
      "issued_at": 2018,
      "assigned_by": "ACE"
    }
}

###  Delete User (Admin Only)
DELETE {{apiUrl}}/users/68e396f085fe274c0a52e621
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### ========================================
### ROLE MANAGEMENT (ADMIN ONLY)
### =======================================

###  Get Users by Athlete Role 
GET {{apiUrl}}/roles/athlete/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

###  Get Users by Coach Role
GET {{apiUrl}}/roles/coach/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

###  Get Users by Gym Role
GET {{apiUrl}}/roles/gym/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

###  Get Users by Admin Role
GET {{apiUrl}}/roles/admin/users
Authorization: Bearer {{adminToken}}
Content-Type: application/json

### Get Role Statistics
GET {{apiUrl}}/roles/statistics
Authorization: Bearer {{adminToken}}
Content-Type: application/json

###  Update User Role
PUT {{apiUrl}}/users/68e63d464aa3385bfd0c7456/role
Authorization: Bearer {{adminToken}}
Content-Type: application/json
  
{
  "newRole": "admin"
}

###  Approve User
PUT {{apiUrl}}/users/68e63d564aa3385bfd0c7459/approve
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "is_Approved": true
}

###  Toggle User Status
PUT {{apiUrl}}/users/68e63cfb2b198091eec4cd73/status
Authorization: Bearer {{adminToken}}  
Content-Type: application/json

### ========================================
### COACH ROUTES
### ========================================

###  Create Coach
POST {{apiUrl}}/coaches
Content-Type: application/json

{
  "name": "Karim Karimi",
  "email": "karim.karimi@example.com",
  "password": "myPass123",
  "gender": "male",
  "cin": "KY789012",
  "years_of_experience": 4,
  "specialization": "Cardio",
  "profile": {
    "avatar": "https://example.com/karim.jpg",
    "bio": "Coach spécialisé en préparation physique."
  },
  "certificates": [
    {
      "title": "Personal Trainer Certification",
      "assigned_by": "Fitness Academy",
      "issued_at": "2020-08-10"
    }
  ]
}

###  Get All Coaches
GET {{apiUrl}}/coaches
Content-Type: application/json

###  Get Coach by ID
GET {{apiUrl}}/coaches/68fb53964b256da6d94ef035
Content-Type: application/json

###  Update Coach
PATCH {{apiUrl}}/coaches/68fb53964b256da6d94ef035
Content-Type: application/json

{
  "certificates": [
    {
      "title": "Musculation Trainer Certification",
      "assigned_by": "Fitness Academy",
      "issued_at": "2020-08-10"
    },
    {
      "title": "Advanced Nutrition Certification",
      "assigned_by": "Health Institute",
      "issued_at": "2022-03-15"
    }
  ]
}

###  Delete Coach
DELETE {{apiUrl}}/coaches/68dfa65751d4286f87e1d936
Content-Type: application/json

### ========================================
### GYM ROUTES
### ========================================

###  Create Gym
POST {{apiUrl}}/gyms
Content-Type: application/json

{
  "name": "FitClub Casablanca",
  "location": "10 Rue de Ghandi",
  "schedule": "Lun-Sam: 07:00-22:00",
  "pricing": 39.99,
  "activities": ["musculation", "cardio"],
  "equipements": ["660a1b2c3d4e5f6a7b8c9d0e"],
  "owner": "68fb4bc7ceef7f0d5a7c26b1"
}

###  Get All Gyms
GET {{apiUrl}}/gyms?owner=68fb4bc7ceef7f0d5a7c26b1
Content-Type: application/json

###  Get Gym by ID
GET {{apiUrl}}/gyms/68ff5239186354e33d34c93f
Content-Type: application/json

### Update Gym
PATCH {{apiUrl}}/gyms/6901e06419cd1ad9ef4981d0
Content-Type: application/json

{
  "coaches": [
    "68fb53964b256da6d94ef035"
    ]
}

###  Delete Gym
DELETE {{apiUrl}}/gyms/68e768c97d8e8605b37eb119
Content-Type: application/json

### ========================================
### Association Coach ↔ Gym
### ========================================

###  Attach a coach to a gym
PATCH {{apiUrl}}/coaches/6900a3a1d0fdb287eccab13a/gym
Content-Type: application/json

{
  "gymId": "68ff5239186354e33d34c93f"
}

###  Detach a coach from a gym
PATCH {{apiUrl}}/coaches/68e4f52f556a398af4724113/gym/remove
Content-Type: application/json

{
  "gymId": "68dfa673f9ab81b206322aff"
}

###  Get all coaches of a specific gym
GET {{apiUrl}}/gyms/68ff5239186354e33d34c93f/coaches
Content-Type: application/json

### ========================================
### Endpoints consultation
### ========================================

### Get all gyms for an athlete
GET {{apiUrl}}/athletes/68dfa65751d4286f87e1d956/gyms
Content-Type: application/json

### Get all coaches for an athlete
GET {{apiUrl}}/athletes/68dfa65751d4286f87e1d956/coaches
Content-Type: application/json

### ========================================
### ADMIN ROUTES
### ========================================

###  Get All Users (Admin)
GET {{ baseUrl }}/api/admin/programs
Content-Type: application/json
Authorization: {{auth}}

###
PUT {{baseUrl}}/api/admin/:id/status
Content-Type: application/json
Authorization: {{auth}}

###get users
GET {{baseUrl}}/api/admin/users
Content-Type: application/json
Authorization: {{auth}}

###activate user
PATCH {{baseUrl }}/api/admin/users/68e4ec06a14e061216b1dbf2/activate
Content-Type: application/json
Authorization: {{auth}}

###deactivate account
PATCH {{baseUrl }}/api/admin/users/68e4ec06a14e061216b1dbf2/deactivate
Content-Type: application/json
Authorization: {{auth}}

###delete user
DELETE  {{baseUrl}}/api/admin/users/68e4ec06a14e061216b1dbf2
Authorization: {{auth}}

###statistiques des users/activeUsers/inactiveUsers/coaches/gyms
GET {{baseUrl}}/api/admin/stats
Content-Type: application/json
Authorization: {{auth}}

### ========================================
### PROGRAM ROUTES
### ========================================
### program paginate
GET {{baseUrl}}/api/programs?page=2&limit=2&price[gte]=40&creator=1&blabla=2&search=youssef
Content-Type: application/json


### program show
GET {{baseUrl}}/api/programs/68e77dceabf27716320ab8c6
Content-Type: application/json
Authorization: Bearer {{adminToken}}

### program create 
POST {{baseUrl}}/api/programs
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "title for program",
  "program_goals": [
    "strenght",
    "lwiza",
    "lhmss"
  ],
  "price": "44",
  "period": 50,
  "status": "pending"
}


### program update 
PUT {{baseUrl}}/api/programs/68e531c711d5e93ef6d311da
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "title": "title for program (updated)",
  "program_goals": [
    "strenght",
    "lwiza",
    "lhmss"
  ],
  "price": "44",
  "period": 50,
  "status": "pending"
}


### program update  (toggle active state)
PUT {{baseUrl}}/api/programs/68e531c711d5e93ef6d311da
Content-Type: application/json
Authorization: Bearer {{adminToken}}

{
  "active": false
}

### delete program 
DELETE {{baseUrl}}/api/programs/68e531c711d5e93ef6d311da
Content-Type: application/json
Authorization: Bearer {{adminToken}}


### ========================================
### PAYMENT ROUTES
### ========================================

### payment checkout (test this in the browser for redirection)
GET {{baseUrl}}/api/payments/programs/68e5334711d5e93ef6d311fb/checkout
Content-Type: application/json


### ========================================
### SERVER HEALTH CHECK
### ========================================

###  Server Health Check
GET {{baseUrl}}/
Content-Type: application/json

