### test
@baseUrl = http://localhost:5000
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4Zjc5YTlmYTMzZmUwZWQ2OWIyNzYyNSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MTA1OTUwMSwiZXhwIjoxNzYyMzU1NTAxfQ.EupOYOLfQHaQ4wr65EFYvpjUwC9xjE5yW5TYz4JLqGU

GET {{ baseUrl }}/api/admin/programs
Content-Type: application/json
Authorization: {{auth}}

###
PUT {{baseUrl}}/api/admin/programs/6672a1b8c5d8e34f8c952a13/status?status=approved
Content-Type: application/json
Authorization: {{auth}}

###get users
GET {{baseUrl}}/api/admin/users
Content-Type: application/json
Authorization: {{auth}}

###activate user
PATCH {{baseUrl }}/api/admin/users/68e4ec06a14e061216b1dbf2/activate
Content-Type: application/json
Authorization: {{auth}}

###deactivate account
PATCH {{baseUrl }}/api/admin/users/68e4ec06a14e061216b1dbf2/deactivate
Content-Type: application/json
Authorization: {{auth}}

###delete user
DELETE  {{baseUrl}}/api/admin/users/68e4ec06a14e061216b1dbf2
Authorization: {{auth}}

###statistiques des users/activeUsers/inactiveUsers/coaches/gyms
GET {{baseUrl}}/api/admin/transactions
Content-Type: application/json
Authorization: {{auth}}