### test
@baseUrl = http://localhost:3000
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTRlNDczMjM1NGM1Y2ZlMzA0MmQzYSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTgzMTIwMSwiZXhwIjoxNzU5ODMyMTAxfQ.gX8hEgWjZOUwQycHMlzFV2Vb0_s8sCErnEjJ-XEzsEw

GET {{ baseUrl }}/api/admin/programs
Content-Type: application/json
Authorization: {{auth}}


