### test
@baseUrl = http://localhost:4000
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZTI5NDRjMWJiZmU3YmUwNzlkN2JiYSIsInJvbGUiOiJjb2FjaCIsImlhdCI6MTc1OTcwMjE1MiwiZXhwIjoxNzU5NzAzMDUyfQ._fHeToh3hZ_TuhCQLcoDhP8S4IzZHPTXHp-y1NV2CTc

GET {{ baseUrl }}
Content-Type: application/json


##################################### Auth #####################################
### register
POST {{ baseUrl }}/api/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "password": "SecurePass123!",
  "role": "coach",
  "gender": "male",
  "cin": "EE123456",
  "years_of_experience": 5
}

### login
POST {{ baseUrl }}/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "SecurePass123!"
}




##################################### Payment #####################################
### payment checkout
GET {{baseUrl}}/api/programs/68e03685fcedd282eeb7c320/checkout
Content-Type: application/json



##################################### Program ##################################
### program paginate
GET {{baseUrl}}/api/programs?page=2&limit=2&price[gte]=40&creator=1&blabla=2&search=youssef
Content-Type: application/json



### program create 
POST {{baseUrl}}/api/programs
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "title for program",
  "program_goals": [
    "strenght",
    "lwiza",
    "lhmss"
  ],
  "price": "44",
  "period": 50,
  "status": "pending"
}


### program update 
PUT {{baseUrl}}/api/programs/68e2945b1bbfe7be079d7bbd
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "title for program (updated)",
  "program_goals": [
    "strenght",
    "lwiza",
    "lhmss"
  ],
  "price": "44",
  "period": 50,
  "status": "pending"
}


### program update  (toggle active state)
PUT {{baseUrl}}/api/programs/68e2945b1bbfe7be079d7bbd
Content-Type: application/json
Authorization: {{auth}}

{
  "active": true
}

### delete program 
DELETE {{baseUrl}}/api/programs/68e2945b1bbfe7be079d7bbd
Content-Type: application/json
Authorization: {{auth}}
