### test
@baseUrl = http://localhost:5000
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MGY2OTEzMmMwNTE0ZWY3NzE1OTkxMSIsInJvbGUiOiJhdGhsZXRlIiwiaWF0IjoxNzYyNjE3NzMwLCJleHAiOjE3NjI2MTg2MzB9.aU4K3_e64giClXZNCd2KlTT9JxlGhbQ8yHwxdcOPOUw

GET {{ baseUrl }}
Content-Type: application/json


##################################### Auth #####################################
### register
POST {{ baseUrl }}/api/auth/signup
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jfohn.doe@example.com",
  "password": "SecurePass123!",
  "role": "athlete",
  "gender": "male",
  "cin": "EE123456",
  "years_of_experience": 5
}

### login
POST {{ baseUrl }}/api/auth/login
Content-Type: application/json

{
  "email": "jfohn.doe@example.com",
  "password": "SecurePass123!"
}




##################################### Payment #####################################
### payment checkout
GET {{baseUrl}}/api/payments/programs/68fa19ebaf91a5fd042f02ec/checkout
Content-Type: application/json


##################################### Program ##################################
### program paginate
GET {{baseUrl}}/api/programs?page=2&limit=2&price[gte]=40&creator=1&blabla=2&search=youssef
Content-Type: application/json


### program show
GET {{baseUrl}}/api/programs/68e77dceabf27716320ab8c6
Content-Type: application/json
Authorization: {{auth}}

### program create 
POST {{baseUrl}}/api/programs
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "title for program",
  "program_goals": [
    "strenght",
    "lwiza",
    "lhmss"
  ],
  "price": "44",
  "period": 50,
  "status": "pending"
}


### program update 
PUT {{baseUrl}}/api/programs/68e531c711d5e93ef6d311da
Content-Type: application/json
Authorization: {{auth}}

{
  "title": "title for program (updated)",
  "program_goals": [
    "strenght",
    "lwiza",
    "lhmss"
  ],
  "price": "44",
  "period": 50,
  "status": "pending"
}


### program update  (toggle active state)
PUT {{baseUrl}}/api/programs/68e531c711d5e93ef6d311da
Content-Type: application/json
Authorization: {{auth}}

{
  "active": false
}

### delete program 
DELETE {{baseUrl}}/api/programs/68e531c711d5e93ef6d311da
Content-Type: application/json
Authorization: {{auth}}
