### test
@baseUrl = http://localhost:3000
GET {{baseUrl}}
Content-Type: application/json


### payment checkout

GET {{baseUrl}}/api/programs/68e03685fcedd282eeb7c320/checkout
Content-Type: application/json