import mongoose from "mongoose";
import connectDB from "../config/db.js";
import Program from "../models/Program.js";

// Connect to DB
await connectDB();

const programs = [
  {
    title: "Full Body Transformation",
    image: "/uploads/programs/fullbody.jpg",
    file: "/uploads/files/fullbody-plan.pdf",
    creator: "672f9a0d8b3215a2b6a41201",
    goals: ["Build muscle", "Increase stamina", "Lose fat"],
    price: 49.99,
    period: 30,
    active: true,
    status: "approved",
  },
  {
    title: "Lean Muscle Challenge",
    image: "/uploads/programs/leanmuscle.jpg",
    file: "/uploads/files/leanmuscle-guide.pdf",
    creator: "672f9a0d8b3215a2b6a41201",
    goals: ["Gain lean mass", "Improve strength"],
    price: 59.99,
    period: 45,
    active: true,
    status: "approved",
  },
  {
    title: "Fat Burn Express",
    image: "/uploads/programs/fatburn.jpg",
    file: "/uploads/files/fatburn-plan.pdf",
    creator: "672f9a0d8b3215a2b6a41201",
    goals: ["Burn fat", "Boost metabolism", "Improve cardio"],
    price: 39.99,
    period: 21,
    active: true,
    status: "approved",
  },
  {
    title: "Home Workout Starter Pack",
    image: "/uploads/programs/homeworkout.jpg",
    file: "/uploads/files/homeworkout-guide.pdf",
    creator: "672f9a0d8b3215a2b6a41202",
    goals: ["Workout from home", "No equipment needed"],
    price: 29.99,
    period: 14,
    active: true,
    status: "approved",
  },
  {
    title: "Strength & Power Program",
    image: "/uploads/programs/strength.jpg",
    file: "/uploads/files/strength-plan.pdf",
    creator: "672f9a0d8b3215a2b6a41202",
    goals: ["Increase strength", "Improve power output"],
    price: 69.99,
    period: 60,
    active: true,
    status: "approved",
  },
  {
    title: "Yoga for Flexibility",
    image: "/uploads/programs/yoga-flex.jpg",
    file: "/uploads/files/yoga-flex.pdf",
    creator: "672f9a0d8b3215a2b6a41203",
    goals: ["Increase flexibility", "Improve balance"],
    price: 34.99,
    period: 21,
    active: true,
    status: "approved",
  },
  {
    title: "HIIT Advanced Program",
    image: "/uploads/programs/hiit-advanced.jpg",
    file: "/uploads/files/hiit-advanced.pdf",
    creator: "672f9a0d8b3215a2b6a41203",
    goals: ["High intensity", "Improve endurance", "Burn calories"],
    price: 44.99,
    period: 28,
    active: true,
    status: "approved",
  },
  {
    title: "Core Strength Builder",
    image: "/uploads/programs/core.jpg",
    file: "/uploads/files/core-strength.pdf",
    creator: "672f9a0d8b3215a2b6a41204",
    goals: ["Build core stability", "Improve posture"],
    price: 39.99,
    period: 25,
    active: true,
    status: "approved",
  },
  {
    title: "Beginner Gym Program",
    image: "/uploads/programs/beginnergym.jpg",
    file: "/uploads/files/beginner-gym.pdf",
    creator: "672f9a0d8b3215a2b6a41204",
    goals: ["Learn fundamentals", "Improve confidence in gym"],
    price: 29.99,
    period: 30,
    active: true,
    status: "approved",
  },
  {
    title: "Mobility & Recovery Routine",
    image: "/uploads/programs/mobility.jpg",
    file: "/uploads/files/mobility.pdf",
    creator: "672f9a0d8b3215a2b6a41205",
    goals: ["Improve recovery", "Enhance mobility"],
    price: 24.99,
    period: 14,
    active: true,
    status: "approved",
  },
  {
    title: "CrossFit Challenge",
    image: "/uploads/programs/crossfit.jpg",
    file: "/uploads/files/crossfit-plan.pdf",
    creator: "672f9a0d8b3215a2b6a41205",
    goals: ["Increase endurance", "Boost overall fitness"],
    price: 74.99,
    period: 45,
    active: true,
    status: "approved",
  },
  {
    title: "Boxing Conditioning Program",
    image: "/uploads/programs/boxing.jpg",
    file: "/uploads/files/boxing-conditioning.pdf",
    creator: "672f9a0d8b3215a2b6a41206",
    goals: ["Improve agility", "Increase coordination", "Build stamina"],
    price: 49.99,
    period: 35,
    active: true,
    status: "approved",
  },
  {
    title: "Mindful Meditation & Yoga",
    image: "/uploads/programs/mindful.jpg",
    file: "/uploads/files/mindful.pdf",
    creator: "672f9a0d8b3215a2b6a41206",
    goals: ["Reduce stress", "Improve mindfulness"],
    price: 19.99,
    period: 10,
    active: true,
    status: "approved",
  },
  {
    title: "Cardio Endurance Mastery",
    image: "/uploads/programs/cardio.jpg",
    file: "/uploads/files/cardio.pdf",
    creator: "672f9a0d8b3215a2b6a41207",
    goals: ["Boost cardiovascular health", "Improve lung capacity"],
    price: 44.99,
    period: 30,
    active: true,
    status: "approved",
  },
  {
    title: "Athlete Performance Plan",
    image: "/uploads/programs/athlete.jpg",
    file: "/uploads/files/athlete-performance.pdf",
    creator: "672f9a0d8b3215a2b6a41207",
    goals: ["Enhance speed", "Improve power", "Boost coordination"],
    price: 89.99,
    period: 60,
    active: true,
    status: "approved",
  },
  {
    title: "Bodyweight Shred",
    image: "/uploads/programs/bodyweight.jpg",
    file: "/uploads/files/bodyweight.pdf",
    creator: "672f9a0d8b3215a2b6a41208",
    goals: ["No equipment", "Full body workouts"],
    price: 34.99,
    period: 21,
    active: true,
    status: "approved",
  },
  {
    title: "Posture Correction Plan",
    image: "/uploads/programs/posture.jpg",
    file: "/uploads/files/posture-correction.pdf",
    creator: "672f9a0d8b3215a2b6a41208",
    goals: ["Fix posture", "Reduce back pain"],
    price: 27.99,
    period: 20,
    active: true,
    status: "approved",
  },
  {
    title: "Summer Body Bootcamp",
    image: "/uploads/programs/summerbody.jpg",
    file: "/uploads/files/summerbody.pdf",
    creator: "672f9a0d8b3215a2b6a41209",
    goals: ["Tone muscles", "Lose fat", "Boost confidence"],
    price: 59.99,
    period: 40,
    active: true,
    status: "approved",
  },
  {
    title: "Endurance for Runners",
    image: "/uploads/programs/runners.jpg",
    file: "/uploads/files/runners-endurance.pdf",
    creator: "672f9a0d8b3215a2b6a41209",
    goals: ["Improve running performance", "Increase endurance"],
    price: 39.99,
    period: 30,
    active: true,
    status: "approved",
  },
  {
    title: "Women’s Strength Program",
    image: "/uploads/programs/womenstrength.jpg",
    file: "/uploads/files/womenstrength.pdf",
    creator: "672f9a0d8b3215a2b6a41210",
    goals: ["Empower women", "Build strength", "Improve confidence"],
    price: 54.99,
    period: 45,
    active: true,
    status: "approved",
  },
];

try {
  // Optional: avoid duplicates by title
  const titles = programs.map((p) => p.title);
  await Program.deleteMany({ title: { $in: titles } });
  const inserted = await Program.insertMany(programs);
  console.log(`Inserted ${inserted.length} programs.`);
} catch (err) {
  console.error("Error inserting programs:", err.message);
} finally {
  await mongoose.disconnect();
}


